services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    image: nodepulse/mq-broker:dev
    container_name: nodepulse-app-dev
    user: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=${APP_ENV:-development}
      - NODE_OPTIONS=--max-old-space-size=${APP_MAX_RAM_MB:-1843}
      - UV_THREADPOOL_SIZE=${APP_THREADS:-4}
      - PORT=${DOCKER_HTTP_PORT:-3000}
      - TCP_PORT=${DOCKER_TCP_PORT:-4000}
      - MAX_RETRIES=${MAX_RETRIES:-5}
    ports:
      - "${HOST_HTTP_PORT:-3000}:${DOCKER_HTTP_PORT:-3000}"
      - "${HOST_TCP_PORT:-4000}:${DOCKER_TCP_PORT:-4000}"
      - "${HOST_DEBUGGER_PORT:-9229}:9229"
    command: >
      sh -c "
      if [ ! -f .env ]; then
        echo '.env is not found, copying from .env.example...';
        cp .env.example .env;
      fi && npm run dev
      "
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    develop:
      watch:
        - action: sync
          path: .
          target: /home/node/app
          ignore:
            - node_modules
        - action: rebuild
          path: package.json
    networks:
      - mq_network
    deploy:
      resources:
        limits:
          cpus: '${DOCKER_CPUS_LIMIT:-1.00}'
          memory: ${DOCKER_MEMORY_LIMIT_MB:-2048}m
        reservations:
          cpus: '${DOCKER_CPUS_RESERVATION:-0.25}'
          memory: ${DOCKER_MEMORY_RESERVATION_MB:-128}m
networks:
  mq_network:
    driver: bridge